### ISSUE TITLE
Support revised Dualshock 4 V2 Model CUH-ZCT2

### ISSUE THREAD

**Issue by Vanquo** [Jays2Kings/DS4Windows#177]
It has a new Product ID. 
VID_054C&PID_09CC

**Comment by TristanYoung** [comment]
It would be nice if the developer would make it so users could add Product ID's themselves as new controllers come out.  I'm sure the DS4 v2 won't be the last version.  A simple .ini file or registry entry would be ok.

**Comment by andersfischernielsen** [comment]
I added the PID to the source code and recompiled. It works for me now using a new DS4. 
I've also made a pull request for adding this to the main release. 👍 

[DS4Windows-new-fixed.zip](https://github.com/Jays2Kings/DS4Windows/files/511673/DS4Windows-new-fixed.zip)

**Comment by andersfischernielsen** [comment]
Fixed in pull request, though Hide DS4 is no longer working:
#179

**Comment by TristanYoung** [comment]
Unfortunately your fix breaks support for the Dualshock 4 v1 controllers.  Since I have two v1's (1 with good triggers, one with bad triggers with replacements en route), and one v2, it's important that v1 and v2 work.

DS4Windows no longer detects my v1 controllers in the main window.

I am reverting to the previous version.

**Comment by TristanYoung** [comment]
Sorry, I made a comment that something broke v1 support, but on checking the changes to the sourcecode, and then reviewing my bluetooth device status, it appears the driver screwed up and stopped working.  I unpaired the controller, and then repaired it, and my v1 controllers are working.

I ended up deleting my comment.  Sorry for that.

**Comment by InstallGentoo11** [comment]
So was this ever fixed?

**Comment by TristanYoung** [comment]
The new DS4 controller has been working flawlessly for me.  Ever since the PID was added, been good.  I have DS4Windows auto-starting through the Windows Scheduler, and only run Steam on demand, so DS4Windows always gets exclusivity, although I could also load steam after DS4Windows through Scheduler with a delay. 

I'm now using a different fork of this project, which has receiving d numerous updates, also been stable. 

Ok to close this one. 


On June 11, 2017 6:07:47 PM EDT, InstallGentoo11 <notifications@github.com> wrote:
>So was this ever fixed?
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/Jays2Kings/DS4Windows/issues/177#issuecomment-307660125

-- 
Music is the art of thinking with sounds

**Comment by Vanquo** [comment]
The fork with numerous updates Tristan mentioned is this https://github.com/Ryochan7/DS4Windows
