### ISSUE TITLE
DS4Windows doesn't start after updating to 2.0

### ISSUE THREAD

**Issue by dmcdonald8** [Jays2Kings/DS4Windows#554]
Just upgraded in-app.

Now nothing happens when I run DS4Windows.exe. No window, no message. DS4Windows process appears in list of running processes then disappears.

I think it would be good if it was easier to roll back versions for issues like this. Maybe having some of the latest releases available for download would help. Last version you can download directly is 1.4.5.2. Which now I need to download and roll back to and I can't update from in case this happens again.

Edit: 
I'm on Windows 10 Pro 64-bit

**Comment by dmcdonald8** [comment]
If anyone else has issues with v2.0 and needs to roll back the version:
Get older version from releases and extract to a new place. Don't run Updater as it will just upgrade to 2.0 and break it again.
Go to the Updates folder in your (broken) v2.0 DS4Windows directory. 
Previous update versions are in there. Pick one and extract the contents to the directory of the older version, it should upgrade it to whatever version you picked.

**Comment by ayala-io** [comment]
You're confusing which DS4Windows you are using. Jays2Kings (this repository) hasn't been updated in 3 years with the last version being 1.4.5.2, and you're not going to get any help posting your issues here.

Version 2.0 is [Ryochan7's fork of DS4Windows](https://github.com/Ryochan7/DS4Windows) which is very active and is the de facto repository for DS4Windows now. If you have any problems, you should post your issue there, not here. Furthermore, the previous versions are found in [Ryochan7's releases](https://github.com/Ryochan7/DS4Windows/releases).

As for your problem, I also had the same issues when updating in-place. Even after rebooting, DS4Windows wouldn't launch. I fixed it by simply downloading v2.0 directly from the website and into a new folder. DS4Windows now launches from my new folder (and I deleted the old one). Version 2 is a major re-write so I expected that updating in-place might have some problems.

**Comment by Ryochan7** [comment]
This was a combination of two different problems regarding the updater. The issues were discovered only about two weeks ago. Due to that, the only safe upgrade path ended up being updating from version 1.7.28 to version 2.0. Trying to update from an older version would lead to an incomplete installation of version 2.0.

The major recourse for people running older versions is to download the fixed DS4Updater and run it in the DS4Windows folder. You can also start from scratch with a new DS4Windows installation. More info about the update can be found at the following link.

https://github.com/Ryochan7/DS4Windows/issues/946

**Comment by GundamApex** [comment]
This is my first time installing this program, so I've never had any version prior to 2.0. I'm having the same problem, and I'm wondering if it has anything to do with installing this while Steam is running. I can't remember if I had Steam up or not (I probably did). If so, is it possible this program would conflict with Steam since Steam also recognizes the DS4 controller and has drivers for it?

I'm also on Windows 10 64 bit and I chose the install to app data option and not portable.

**Comment by Lagrotta85** [comment]
I'm also having the same problem.
Been using 1.7.28 with no problem (only that the updater never works). Now updated manually to 2.0.0 and DS4Windows refuses to start. DS4Windows process appears in list of running processes then disappears. Maybe it is conflicting with some order app running on the background?

Edit: Found out that it was conflicting with MSI Afterburner. Got it to run, but bluetooth is not working, only connection via wire.

Edit2: Got Bluetooth to work normally now. If I run Afterburner after DS4Windows is already running, then I got no problem, both work fine. But when booting windows, if the Afterburner starts first then DS4Windows will not load.

**Comment by ayala-io** [comment]
@GundamApex @Lagrotta85 you should just post your issues in the [Ryochan7's repository](https://github.com/Ryochan7/DS4Windows/issues) where it is more active and you are likely to get help from people who have deep knowledge of how the latest DS4Windows works.

The repository/issue tracker here is dead. I just happen to stop by once in a while to redirect people to the current de facto fork of DS4Windows.
