### ISSUE TITLE
Disable XInput => use DS4 as DS4

### ISSUE THREAD

**Issue by ghost** [Jays2Kings/DS4Windows#90]
The double input issue can be turned off with the 'Hide DS4' option. I would like to do the reverse, hide the XInput-emulated DualShock 4 and use it as a DS4 alone, as if the driver were never installed.

Is this possible? If not, consider this a feature request.

**Comment by SiTWulf** [comment]
You can get these feature now...
Is easy... modify a Profile, and you can see the option "Use Dimput Only".
But the only problem you need to disable the "Hide DS4" option in Settings, but a good idea is making this thing in profiles too... and you can change easily Emulated xBox360 to Real DS4 Profile without open the DS4Windows with Swipe to change profiles.
But you cannot configure the gamepad buttons, because always appears the xbox360 gamepad or keyboard.

**Comment by ghost** [comment]
Thank you very much for your swift and helpful response!

I had no idea that plain DS4 worked merely as a generic DirectInput controller (which means no rumble!). I was under the impression by online commenters that the buttons in Dragon's Dogma: Dark Arisen and Metal Gear Solid V would magically change to DS4 style, but I just tried it and can confirm that's not the case.
